### ISSUE TITLE
Error in hrdev_plugin

### ISSUE THREAD

**Issue by andreafioraldi** [ax330d/hrdev#1]
Hi,
I have copied hrdev.py and the hrdev_plugin folder in [ida path]/plugin/ , but when i try to decompile with alt+f5 ida report a python error in hrdev_plugin `__init__.py` (line 43): "global name hrdev_plugin is not defined".

![virtualbox_cc17-windows-7_09_04_2017_20_35_51](https://cloud.githubusercontent.com/assets/16168186/24840682/a7d75a7c-1d71-11e7-8e84-0946e9704d33.png)

**Comment by gloriouskilka** [comment]
Same issue. Could you write the solution, please?

**Comment by andreafioraldi** [comment]
i don't remember, i don't use hrdev anymore
